### ISSUE TITLE
KeyError: 'invite'

### ISSUE THREAD

**Issue by floviolleau** [madmax28/navi#2]
Hi,

Thanks for this great project.

I have an error on my server using this tool since 16 July 2021.

```
Traceback (most recent call last):
  File "/usr/local/bin/pushelement", line 28, in <module>
    quiet=args.quiet)
  File "/home/user/navi/navi/core.py", line 32, in __init__
    self.token = self.client.login_with_password(self.user_id, self.password)
  File "/home/user/navi/navi/matrix-python-sdk/matrix_client/client.py", line 183, in login_with_password
    self._sync()
  File "/home/user/navi/navi/matrix-python-sdk/matrix_client/client.py", line 429, in _sync
    for room_id, invite_room in response['rooms']['invite'].items():
KeyError: 'invite'
```
I tried to update the matrix-python-sdk to latest master but I have another issue:
```
Traceback (most recent call last):
  File "navi.py", line 35, in <module>
    navi.push_msg(msg)
  File "/home/user/navi/navi/core.py", line 50, in push_msg
    self._cleanup_rooms()
  File "/home/user/navi/navi/core.py", line 95, in _cleanup_rooms
    users = room.get_joined_members().keys()
AttributeError: 'list' object has no attribute 'keys'
```

Any ideas?
Thanks!

**Comment by floviolleau** [comment]
Hi @madmax28,

Any news?

Thanks for your help

**Comment by madmax28** [comment]
Thanks for reporting. I've updated the matrix-python-sdk version and made the necessary changes in c77f57af6400a3bc302af4e4a3ee5bb619a2b6e0.

Hope that solves it for you!

**Comment by floviolleau** [comment]
Super thanks. Works perfectly now

Take care
